### ISSUE TITLE
server: implement json api layer

### ISSUE THREAD

**Issue by sripwoud** [pseXperiments/freedit#5]
Instead of serving directly pre generated html documents, we want to serve the DB data as json and let the client web app build the pages.

Probably not too complicated as the handlers logic are already implemented
More like a big refactor, we need to change the response of these handlers.
We should stop returning rinja templates. E.g [here](https://github.com/pseXperiments/freedit/blob/ecab14e2e7a769f879bffa03c9f165071d8d8620/src/controller/feed.rs#L339), [use of rinja::into_response](https://docs.rs/rinja_axum/0.3.5/rinja_axum/fn.into_response.html)
and send json responses instead.

the existing API seems to be documented as comments/docstrings already in each handler file.

**Comment by sripwoud** [comment]
cc @adria0

**Comment by AtHeartEngineer** [comment]
@sripwoud I think making new endpoints such as `/api/v1/profile` or whatever might be a better option. At some point we would have to turn of the front end ran by freedit and switch to our own front end, but at least in this way we could keep a separation between the two while the work is being done on it.

The new front end while its in alpha could be at `forum.pse.dev/new` or something like that.

Just some thoughts.

**Comment by sripwoud** [comment]
Oh yes you are right that is better!

**Comment by sripwoud** [comment]
transferred to https://github.com/privacy-scaling-explorations/pse-forums/issues/5
